name: Backend API Tests

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install fastapi
          pip install uvicorn
          pip install pytest
          pip install httpx
          pip install pytest-asyncio
          pip install pytest-cov
          pip install python-jose[cryptography]

      - name: Run tests
        run: |
          pytest